# Generated by Django 4.2.2 on 2023-06-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('accounttype', models.CharField(max_length=250)),
                ('materials', models.CharField(max_length=250)),
            ],
        ),
    ]
