# Generated by Django 4.2.2 on 2023-06-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='branch',
            new_name='dbranch',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='email',
            new_name='emailid',
        ),
    ]
